branch-defaults:
  master:
    environment: Jenkinslearninglog-env
environment-defaults:
  Jenkinslearninglog-env:
    branch: null
    repository: null
global:
  application_name: Jenkins-LearningLog
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
